import requests
import os
from urllib.parse import urlparse


def download_json_file(url):
    response = requests.get(url)
    if response.status_code == 200:
        # Extract the filename from the URL
        parsed_url = urlparse(url)
        path = "D:\\BlockStars\\5 Lions\\"+parsed_url.path
        directory = os.path.dirname(path)
        os.makedirs(directory, exist_ok=True)
        # Save the file with the desired name
        with open(path, 'wb') as file:
            file.write(response.content)
        print(f"Downloaded: {path}")
    else:
        print(f"Failed to download: {url}")


# List of JSON file links
json_links = [
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/cs3irishcharms/cs3irishcharms_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/cs5triple8gold/cs5triple8gold_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs100firehot/vs100firehot_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs100sh/vs100sh_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs1024dtiger/vs1024dtiger_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs1024gmayhem/vs1024gmayhem_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs1024lionsd/vs1024lionsd_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs1024temuj/vs1024temuj_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10amm/vs10amm_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10bbbonanza/vs10bbbonanza_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10bbextreme/vs10bbextreme_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10bbkir/vs10bbkir_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10bookfallen/vs10bookfallen_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10bookoftut/vs10bookoftut_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10bookviking/vs10bookviking_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10bxmasbnza/vs10bxmasbnza_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10cowgold/vs10cowgold_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10crownfire/vs10crownfire_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10egrich/vs10egrich_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10egypt/vs10egypt_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10egyptcls/vs10egyptcls_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10eyestorm/vs10eyestorm_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10fdrasbf/vs10fdrasbf_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10firestrike/vs10firestrike_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10firestrike2/vs10firestrike2_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10floatdrg/vs10floatdrg_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10fruity2/vs10fruity2_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10goldfish/vs10goldfish_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10luckcharm/vs10luckcharm_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10madame/vs10madame_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10mayangods/vs10mayangods_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10mmm/vs10mmm_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10nudgeit/vs10nudgeit_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10returndead/vs10returndead_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10runes/vs10runes_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10spiritadv/vs10spiritadv_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10starpirate/vs10starpirate_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10tictac/vs10tictac_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10tut/vs10tut_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10txbigbass/vs10txbigbass_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10vampwolf/vs10vampwolf_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs10wildtut/vs10wildtut_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs117649starz/vs117649starz_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs12bbb/vs12bbb_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs13ladyofmoon/vs13ladyofmoon_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs15diamond/vs15diamond_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs15fairytale/vs15fairytale_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs15godsofwar/vs15godsofwar_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs1600drago/vs1600drago_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs18mashang/vs18mashang_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs1dragon8/vs1dragon8_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs1fortunetree/vs1fortunetree_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs1masterjoker/vs1masterjoker_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs1tigers/vs1tigers_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20aladdinsorc/vs20aladdinsorc_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20amuleteg/vs20amuleteg_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20bchprty/vs20bchprty_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20beefed/vs20beefed_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20bermuda/vs20bermuda_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20chickdrop/vs20chickdrop_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20chicken/vs20chicken_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20cleocatra/vs20cleocatra_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20clspwrndg/vs20clspwrndg_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20clustwild/vs20clustwild_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20daydead/vs20daydead_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20doghouse/vs20doghouse_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20drgbless/vs20drgbless_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20drtgold/vs20drtgold_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20dugems/vs20dugems_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20egypt/vs20egypt_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20egypttrs/vs20egypttrs_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20eightdragons/vs20eightdragons_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20eking/vs20eking_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20ekingrr/vs20ekingrr_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20emptybank/vs20emptybank_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20farmfest/vs20farmfest_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20fparty2/vs20fparty2_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20fruitparty/vs20fruitparty_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20fruitpartyh/vs20fruitpartyh_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20fruitsw/vs20fruitsw_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20fruitswh/vs20fruitswh_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20gobnudge/vs20gobnudge_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20godiva/vs20godiva_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20goldfever/vs20goldfever_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20goldfeverh/vs20goldfeverh_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20hburnhs/vs20hburnhs_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20hercpeg/vs20hercpeg_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20honey/vs20honey_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20hstgldngt/vs20hstgldngt_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20jewelparty/vs20jewelparty_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20kraken/vs20kraken_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20kraken2/vs20kraken2_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20leprexmas/vs20leprexmas_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20ltng/vs20ltng_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20magicpot/vs20magicpot_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20midas/vs20midas_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20mparty/vs20mparty_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20mtreasure/vs20mtreasure_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20muertos/vs20muertos_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20mustanggld2/vs20mustanggld2_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20mysteryst/vs20mysteryst_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20octobeer/vs20octobeer_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20olympgate/vs20olympgate_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20olympgateh/vs20olympgateh_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20pblinders/vs20pblinders_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20phoenixf/vs20phoenixf_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20rainbowg/vs20rainbowg_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20rhino/vs20rhino_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20rhinoluxe/vs20rhinoluxe_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20rockvegas/vs20rockvegas_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20rome/vs20rome_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20santa/vs20santa_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20santawonder/vs20santawonder_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20sbxmas/vs20sbxmas_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20schristmas/vs20schristmas_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20sknights/vs20sknights_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20smugcove/vs20smugcove_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20starlight/vs20starlight_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20stickysymbol/vs20stickysymbol_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20sugarrush/vs20sugarrush_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20sugarrushh/vs20sugarrushh_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20superx/vs20superx_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20swordofares/vs20swordofares_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20trsbox/vs20trsbox_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20trswild2/vs20trswild2_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20ultim5/vs20ultim5_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20underground/vs20underground_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20wildboost/vs20wildboost_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20wildpix/vs20wildpix_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20wolfie/vs20wolfie_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs20xmascarol/vs20xmascarol_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs243crystalcave/vs243crystalcave_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs243dancingpar/vs243dancingpar_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs243fortseren/vs243fortseren_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs243fortune/vs243fortune_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs243lions/vs243lions_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs243lionsgold/vs243lionsgold_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs243mwarrior/vs243mwarrior_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs243queenie/vs243queenie_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25asgard/vs25asgard_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25bkofkngdm/vs25bkofkngdm_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25bomb/vs25bomb_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25btygold/vs25btygold_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25chilli/vs25chilli_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25copsrobbers/vs25copsrobbers_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25davinci/vs25davinci_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25dragonkingdom/vs25dragonkingdom_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25dwarves/vs25dwarves_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25gladiator/vs25gladiator_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25goldparty/vs25goldparty_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25goldrush/vs25goldrush_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25hotfiesta/vs25hotfiesta_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25jokerking/vs25jokerking_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25kfruit/vs25kfruit_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25mmouse/vs25mmouse_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25mustang/vs25mustang_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25newyear/vs25newyear_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25pandagold/vs25pandagold_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25pandatemple/vs25pandatemple_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25pantherqueen/vs25pantherqueen_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25peking/vs25peking_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25pyramid/vs25pyramid_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25rio/vs25rio_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25rlbank/vs25rlbank_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25scarabqueen/vs25scarabqueen_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25sea/vs25sea_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25spgldways/vs25spgldways_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25walker/vs25walker_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25wildspells/vs25wildspells_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs25wolfgold/vs25wolfgold_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs30catz/vs30catz_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs4096bufking/vs4096bufking_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs4096bufkingh/vs4096bufkingh_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs4096jurassic/vs4096jurassic_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs4096magician/vs4096magician_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs4096mystery/vs4096mystery_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs40bigjuan/vs40bigjuan_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs40cleoeye/vs40cleoeye_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs40cosmiccash/vs40cosmiccash_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs40firehot/vs40firehot_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs40hotburnx/vs40hotburnx_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs40madwheel/vs40madwheel_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs40mstrwild/vs40mstrwild_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs40pirate/vs40pirate_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs40pirgold/vs40pirgold_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs40spartaking/vs40spartaking_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs40streetracer/vs40streetracer_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs40voodoo/vs40voodoo_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs40wildwest/vs40wildwest_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs40wildwesth/vs40wildwesth_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs432congocash/vs432congocash_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs50aladdin/vs50aladdin_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs50amt/vs50amt_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs50hercules/vs50hercules_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs50juicyfr/vs50juicyfr_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs50kingkong/vs50kingkong_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs50mightra/vs50mightra_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs50northgard/vs50northgard_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs576treasures/vs576treasures_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs5aztecgems/vs5aztecgems_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs5drhs/vs5drhs_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs5firehot/vs5firehot_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs5hotburn/vs5hotburn_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs5joker/vs5joker_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs5littlegem/vs5littlegem_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs5spjoker/vs5spjoker_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs5strh/vs5strh_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs5super7/vs5super7_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs5trjokers/vs5trjokers_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs5ultra/vs5ultra_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs5ultrab/vs5ultrab_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs7776aztec/vs7776aztec_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs7776secrets/vs7776secrets_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs7fire88/vs7fire88_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs7monkeys/vs7monkeys_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs7pigs/vs7pigs_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs9aztecgemsdx/vs9aztecgemsdx_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs9catz/vs9catz_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs9chen/vs9chen_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vs9piggybank/vs9piggybank_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswaysbankbonz/vswaysbankbonz_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswaysbbb/vswaysbbb_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswaysbook/vswaysbook_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswaysbufking/vswaysbufking_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswayschilheat/vswayschilheat_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswaysconcoll/vswaysconcoll_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswayscryscav/vswayscryscav_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswaysdogs/vswaysdogs_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswaysdogsh/vswaysdogsh_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswayselements/vswayselements_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswaysfltdrg/vswaysfltdrg_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswaysfrywld/vswaysfrywld_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswaysfuryodin/vswaysfuryodin_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswayshammthor/vswayshammthor_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswayshive/vswayshive_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswaysjkrdrop/vswaysjkrdrop_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswayslight/vswayslight_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswayslions/vswayslions_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswayslionsh/vswayslionsh_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswaysmadame/vswaysmadame_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswaysmadameh/vswaysmadameh_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswayspizza/vswayspizza_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswaysredqueen/vswaysredqueen_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswaysrhino/vswaysrhino_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswaysstrwild/vswaysstrwild_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswayswerewolf/vswayswerewolf_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswayswest/vswayswest_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswayswildwest/vswayswildwest_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswayswwhex/vswayswwhex_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswaysxjuicy/vswaysxjuicy_narrow.jpg",
    "https://common-static.pragmaticplay.net/gs2c/lobby/icons/vswaysyumyum/vswaysyumyum_narrow.jpg",

    # Add more links as needed
]

# Create a directory to store the downloaded files


# Download each JSON file
for link in json_links:
    download_json_file(link)

print("All files downloaded successfully.")
